# Committee roles, volunteering and student society positions.

- "**Postgraduate Representative**, Sri Lankan Student Society, University of Wollongong, Australia."
- "**Logistics Coordinator** , IEEE [ICIIS](http://iciis.org/) Conference 2019."
- "**Student Ambassador**, IEEE PES Day 2018."
- "**Logistics Coordinator** , IEEE [ICIIS](http://iciis.org/) Conference 2017."
- "**Chairman**, IEEE Student Branch, University of Peradeniya, Sri Lanka (2017/18)."
- "**Vice President**, IEEE Student Branch, University of Peradeniya, Sri Lanka (2016/17)."
